### PR TITLE
fix linting errors

### PR DESCRIPTION
**Pull request by p3732**
Hej, really like that you forked this, since the original is not really worked on anymore, thanks for that!

I wanted to give the packaging for F-Droid (#6) a shot (although I have no experience with Android development) and have most things are ready, however, I encountered multiple errors upon compiling with the generic `gradle build` (gradle 4.7 on Arch)

All errors are linting errors, most due to untranslated strings. Another error is
> [...]/KeikaiLauncher/app/src/main/res/layout/activity_search.xml:52: Error: Invalid resource type, expected integer value [InvalidImeActionId]
>               android:imeActionId="@+id/actionGo"
Which I tried to fix according with some help from stackoverflow (https://stackoverflow.com/questions/19753910/)

Hope the changes are alright!

### CODE REVIEW

**Comment by avuton** [comment]
First of all, thank you so much for taking the time to send a PR. Unfortunately, I only continued this project in the first place for my own needs. Launchers have gotten way too unnecessarily complex, and I liked the simplicity that this launcher brought. With all that said, Android has gotten to messy for me to continue working on it and I've got a kid coming soon. Life is too busy for me to continue development, so I'll keep it open but I won't update it anymore unless compilation begins breaking, or someone forks it and improves on it.

**Comment by p3732** [comment]
Okay, I understand, thanks for responding to the PR. Is it alright with you if I use my fork to submit to F-Droid then? I have no real intend to continue development, but I want to give this fork some visibility, so maybe someone else decides to continue working on it (The current state of the project did not compile due to linting errors, that's why I created the PR in the first place).
Enjoy your upcoming parenthood!

**Comment by avuton** [comment]
Nothing would make me happier than to see a fork of this continue to grow on F-Droid and otherwise.  Best of luck!

**Comment by avuton** [comment]
One final thing, if you're interested in continuing the actual maintenance of this package, I think commit e1f119f is flawed; I was wrong in the commit message about it speeding up the launcher, it actually slows it down considerably in some circumstances. A patch like it was necessary due to changes in Android. I don't recall all the details as to the why and everything, but it's been something that's been on my mind since I made this commit. It's something to look at if you're interested in a speedup.

**Pull request closed without merging**
